### ISSUE TITLE
Compilation errors in GtkStatusIcon.vala

### ISSUE THREAD

**Issue by flowernert** [mbt/alltray#6]
Hi there, thanks for this neat piece of software allowing me to get spotify back to my trayzone :)

I compiled from the master branch (commit dfc045b7e47f0112c7c2161c8bdc19c8edade929) and had the following error many times during GtkStatusIcon.vala processing
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
Vala compiler 0.30.1

GtkStatusIcon.vala:45.35-45.42: error: `MenuItem' is an ambiguous reference between `GLib.MenuItem' and `Gtk.MenuItem'
...
GtkStatusIcon.vala:71.26-71.29: error: `Menu' is an ambiguous reference between `GLib.Menu' and `Gtk.Menu'
...

I fixed it by adding the Gtk namespacing at the lines referencing an error, like this for example at line 71
old : Menu ret = new Menu();
new : Gtk.Menu ret = new Gtk.Menu();

After fixing the namespacing everywhere required in the file, alltray compiled just fine.

I'll propose a pull request when I find time to

**Comment by mbt** [comment]
PR merged, closing.
